### ISSUE TITLE
Links inside headings not rendered inside search view

### ISSUE THREAD

**Issue by N3C2L** [ivan-lednev/better-search-views#33] opened 2024-05-04 20:51 UTC
How to repro:

1. Create a heading with links inside.
2. Search for that file.
3. Markdown won't be rendered in headings with links inside the search view.

**Comment by ivan-lednev** [comment] 2024-06-04 08:24
Hello, @N3C2L, please attach some screenshots.

**Comment by N3C2L** [comment] 2024-06-04 08:56
Of couse. Here is a heading 1 in a note (opened in  sandbox vault, with only your plugin installed, then restarted the sandbox vault for taking effect of you plugin), below the same line but not as a heading:

<img width="346" alt="2024-06-04 10_50_18-Footnote - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/ivan-lednev/better-search-views/assets/74585843/5dad4614-243b-459a-9ab0-0079f85bc6a7">


Here is the search result with the  rendered link inside the note, but not rendered in the heading above:

<img width="224" alt="2024-06-04 10_50_22-Footnote - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/ivan-lednev/better-search-views/assets/74585843/f1b5bbd7-78d0-47f8-99d7-3d17c910df87">

It occurs on every heading 1-6.

**Comment by ivan-lednev** [comment] 2024-06-04 11:17
Okay, I see what you mean now. Closing it as a duplicate of #13.

**Closed by ivan-lednev** 2024-06-04 11:17 UTC
