### ISSUE TITLE
Not working on Obsidian Version 1.7.4 !!!

### ISSUE THREAD

**Issue by meomuop98** [ivan-lednev/better-search-views#39] opened 2024-10-18 06:35 UTC
This Plug-in is not working on Obsidian Version 1.7.4 anymore, neither desktop nor mobile (only work on 1.6.7 and earlier verions). Please fix this, thank you so much.

**Comment by meomuop98** [comment] 2024-10-20 03:53
![image](https://github.com/user-attachments/assets/567021bd-2892-44f1-9e79-71bb718efc5e)
You have to disable the "Show more Context" function to keep it working !

**Comment by bhopmann** [comment] 2024-10-20 15:37
For me disabling "Show more context" doesn't work (it was even deactivated before).

**Comment by meomuop98** [comment] 2024-10-20 16:13
> For me disabling "Show more context" doesn't work (it was even deactivated before).

You have to search something in the search box and then it will work again

**Comment by bhopmann** [comment] 2024-10-22 06:27
> > For me disabling "Show more context" doesn't work (it was even deactivated before).
> 
> You have to search something in the search box and then it will work again

Thank you, with doing a quick search it is working now.

**Comment by meomuop98** [comment] 2024-11-11 23:15
here is how to fix it: update to version 1.7.5 !!!

**Comment by ivan-lednev** [comment] 2024-12-01 13:36
Duplicate of #40

**Closed by ivan-lednev** 2024-12-01 13:36 UTC
